name: test_reporter
resolution: workspace
description: CLI Utility to wrap dart tests with reporter plugins. Extend to any report formats with special TestReporter class.
version: 1.3.0
repository: https://github.com/rIIh/dart_test_reporter
issue_tracker: https://github.com/rIIh/dart_test_reporter/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+%5Btest_reporter%5D

environment:
  sdk: ^3.5.0

dependencies:
  path: ^1.8.0
  uuid: ^4.4.0
  freezed_annotation: ^3.1.0
  args: ^2.5.0
  universal_io: ^2.2.2
  ansicolor: ^2.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0

  # codegen
  build_runner: ^2.4.11
  freezed: ^3.2.0
  json_serializable: ^6.8.0

executables:
  test_reporter:
