name: alchemist_test_reporter
description: Alchemist Test Reporter Addon
version: 1.2.0
homepage: https://github.com/rIIh/dart_test_reporter
issue_tracker: https://github.com/rIIh/dart_test_reporter/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+%5Balchemist_test_reporter%5D

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

  alchemist: ^0.12.0
  test: ^1.24.0
  path: ^1.0.0
  image: ^4.2.0
  diff_image2: ^1.2.1


dev_dependencies:
  lints: ^3.0.0