name: allure_report
resolution: workspace
description: Allure Report Adapter. Use it with [test_reporter](https://pub.dev/packages/test_reporter) package
version: 1.3.0
repository: https://github.com/rIIh/dart_test_reporter
issue_tracker: https://github.com/rIIh/dart_test_reporter/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+%5Ballure_report%5D

environment:
  sdk: ^3.5.0

dependencies:
  path: ^1.9.0
  freezed_annotation: ^3.1.0
  test_reporter: ^1.2.0
  universal_io: ^2.2.2
  uuid: ^4.4.0
  mime: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^3.2.0
  lints: ^6.0.0
  test: ^1.24.0
