name: plain_dart_package
resolution: workspace
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  allure_report: ^1.4.0
  test_reporter: ^1.3.0
  lints: ^6.0.0
  test: ^1.24.0
